name: 'Development Branch Protection'
description: 'Protección para branches de desarrollo del proyecto CRM Pyme'
target: branch
enforcement: active

conditions:
  ref_name:
    include:
      - 'develop'
      - 'development'
      - 'dev'
      - 'feature/*'
      - 'bugfix/*'
      - 'hotfix/*'

rules:
  # Requerir Pull Request antes del merge
  - id: require-pull-request-dev
    type: pull_request
    parameters:
      required_approving_review_count: 1
      dismiss_stale_reviews_on_push: true
      require_last_push_approval: true

  # Requerir que los status checks pasen
  - id: require-status-checks-dev
    type: status_check
    parameters:
      required_status_checks:
        - context: 'dotnet-build'
      strict_required_status_checks_policy: true
      require_branches_to_be_up_to_date: true

  # Restricciones de archivos sensibles
  - id: restrict-sensitive-files-dev
    type: file_pattern
    parameters:
      restricted_paths:
        - 'appsettings.Production.json'
        - '*.key'
        - 'secrets/'
        - '*.pem'

  # Restricciones de tamaño de archivo
  - id: file-size-limits-dev
    type: file_pattern
    parameters:
      max_file_size: 104857600  # 100MB
      restricted_paths:
        - '*.zip'
        - '*.rar'
        - '*.7z'

bypass_actors:
  - actor_id: a-nxwball
    actor_type: 'User'
    bypass_mode: 'always'