name: 'Feature Branch Protection'
description: 'Protección para branches de nuevas funcionalidades'
target: branch
enforcement: active

conditions:
  ref_name:
    include:
      - 'feature/*'
      - 'feat/*'

rules:
  # Requerir Pull Request antes del merge
  - id: require-pull-request-feature
    type: pull_request
    parameters:
      required_approving_review_count: 1
      dismiss_stale_reviews_on_push: true

  # Requerir que los status checks pasen
  - id: require-status-checks-feature
    type: status_check
    parameters:
      required_status_checks:
        - context: 'dotnet-build'
      strict_required_status_checks_policy: true

  # Restricciones de archivos sensibles
  - id: restrict-sensitive-files-feature
    type: file_pattern
    parameters:
      restricted_paths:
        - 'appsettings.Production.json'
        - '*.key'
        - 'secrets/'

bypass_actors:
  - actor_id: a-nxwball
    actor_type: 'User'
    bypass_mode: 'always'