name: 'Tag Protection'
description: 'Protección para tags de versiones del proyecto CRM Pyme'
target: tag
enforcement: active

conditions:
  ref_name:
    include:
      - 'v*'  # Proteger tags que empiecen con 'v'
      - 'release-*'  # Proteger tags de releases

rules:
  # Restricciones de push a tags
  - id: restrict-tag-pushes
    type: push
    parameters:
      bypass_mode: 'off'

  # Requerir firmas para tags
  - id: require-tag-signatures
    type: commit_signature
    parameters: {}

  # Restricciones de creación de tags
  - id: restrict-tag-creation
    type: tag
    parameters:
      allow_force_pushes: false
      allow_deletions: false

bypass_actors:
  - actor_id: a-nxwball
    actor_type: 'User'
    bypass_mode: 'always'